### ISSUE TITLE
complete open source solution?

### ISSUE THREAD

**Issue by guaka** [camptocamp/puppet-openerp#15]
I don't want to use proprietary software on my server.

But "This structure is deployed by a buildout receipt (not opensourced for now)."

Is it possible get this working without buildout?
Is there an alternative to this recipe that works with 100% open source software?

**Comment by wtebbens** [comment]
very good, I agree with not using proprietary software ;-)

the buildout system is free software under the Zope Public License, if you digg into it you will see that, e.g. here in the code it is mentioned: http://downloads.buildout.org/2/bootstrap.py

What I think is that the concrete recipe that C2C is using in this buildout is not published... that's the whole thing. And possibly that's a simple thing, as the recipe is something we may play with, depending on the versions of the various libraries, and software sources we will be using. The OpenERP recipe by anybox (from Georges Racinet - he was at the Open Days as well) might serve as a start.

**Comment by jgrandguillaume** [comment]
Hi,

Thanks for your interest ! All our work is open sourced as always. I corrected the docs accordingly. We do use the Buildout recipe from Anybox here : https://pypi.python.org/pypi/anybox.recipe.openerp

Regards,

**Comment by guaka** [comment]
Cool, good to see! Thanks!
